logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    username: test
    password: test
    connection-timeout: 1s
    template:
      retry:
        enabled: true