logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    username: test
    password: test
    # 生产者重试
    connection-timeout: 1s
    template:
      retry:
        enabled: true
    # 生产者确认
    publisher-confirm-type: none
    publisher-returns: false