logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    username: test
    password: test
    listener:
      simple:
        prefetch: 1 # 能者多劳模式
        acknowledge-mode: auto # 交给AMQP自动处理  根据业务和消息转换自动处理ACK、NACK、REJECT